In [1]:
import torch
import numpy as np

<font size="4" color='yellow'>Scalar</font>

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

<font size="4" color='yellow'>Vector</font>

In [5]:
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

<font size="4" color='yellow'>Matrix</font>

In [8]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

<font size="4" color='yellow'>Tensor</font>

In [11]:
tensor1 = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]]])
tensor1

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [12]:
tensor1.ndim

3

In [13]:
tensor1.shape

torch.Size([1, 3, 3])

In [14]:
tensor2 = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]],
                       [[4,4,4],[5,5,5],[6,6,6]]])
tensor2

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]])

In [15]:
tensor2.ndim

3

In [16]:
tensor2.shape

torch.Size([2, 3, 3])

In [17]:
# dtype

In [18]:
float_tensor = torch.tensor([3,6,9], dtype=torch.float32)

In [19]:
print(float_tensor)
print(float_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [20]:
int_tensor = torch.tensor([2,4,8], dtype=torch.int64)

In [21]:
print(int_tensor)
print(int_tensor.dtype)

tensor([2, 4, 8])
torch.int64


In [22]:
float_tensor * int_tensor

tensor([ 6., 24., 72.])

In [23]:
tensor.device

NameError: name 'tensor' is not defined

<font size="4" color='yellow'>Details about a Created Tensor</font>

In [ ]:
arr = torch.rand(3,4)

In [ ]:
print(arr)
print()
print(f"Datatype of Tensor: {arr.dtype}")
print(f"Shape of Tensor: {arr.shape}")
print(f"Device on which Tensor: {arr.device}")

<font size="4" color='yellow'>Manipulating Tensor</font>

In [ ]:
arr1 = torch.tensor([1,2,3])

In [ ]:
print(f"Addition: {torch.add(arr1,10)}")
print(f"Subtraction: {arr1 - 10}")
print(f"Multiplication: {torch.mul(arr1,10)}")
print(f"Division: {torch.div(arr1,10)}")
print(f"Modulus: {torch.remainder(arr1,10)}")

In [ ]:
# Element-wise multiplication
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([1,2,3])

print(f'Element-wise Multiplication: {arr1 * arr2}')

In [ ]:
# Matrix multiplication
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([1,2,3])

print(f'Matrix Multiplication: {torch.matmul(arr1,arr2)}')

In [ ]:
tensor_arr = torch.arange(1, 10, dtype=torch.float32)
tensor_arr

In [ ]:
tensor_arr.dtype

In [ ]:
print(f'Min: {tensor_arr.min()}')
print(f'Max: {tensor_arr.max()}')
print(f'Sum: {tensor_arr.sum()}')
print(f'Mean: {tensor_arr.mean()}')

In [ ]:
print(f'Position of Smallest Element: {tensor_arr.argmin()}')
print(f'Position of Largest Element: {tensor_arr.argmax()}')
print(f'Sorted Index: {tensor_arr.argsort()}')

In [ ]:
arr = torch.rand(2,3)
arr,arr.shape

In [ ]:
arr = arr.reshape(3,2)
arr, arr.shape

In [ ]:
arr.flatten()

In [ ]:
# after set unsqueeze 1, tensor becomes 2d

tensor = torch.tensor([1,2,3])
arr = tensor.unsqueeze(1)
arr, tensor.shape, arr.shape

In [ ]:
x = arr.squeeze()
x

In [ ]:
# permute
arr = torch.rand(2,4,3)
arr, arr.shape

In [ ]:
permuted_arr = arr.permute(2,0,1)
permuted_arr, permuted_arr.shape

<font size="4" color='yellow'>Indexing</font>

In [ ]:
# Basic Indexing
arr = torch.arange(1,10)
print(arr)
print(arr[0]) # First Element
print(arr[4]) # Element at 4th position
print(arr[-1]) # Last Element

In [ ]:
# Indexing in 2d

arr = torch.rand(2,2)
print(arr)
print(arr[0][0])
print(arr[0][1])
print(arr[1][0])
print(arr[0][1])

In [ ]:
# Indexing in 3d
# 3d = [batch, row, columns]

arr = torch.rand(2,2,2)
print(arr)
print(arr[0][0][0])
print(arr[1][0][0])
print(arr[0][:][:])
print()
print(arr[1][:][:])

<font size="4" color='yellow'>Tensor to Numpy</font>

In [ ]:
tensors = torch.rand([2,2])

In [ ]:
num_arr = tensors.numpy()

In [ ]:
print(num_arr)
print(type(num_arr))

<font size="4" color='yellow'>Numpy to Tensor</font>

In [ ]:
tensors = torch.from_numpy(num_arr)

In [ ]:
print(tensors)
print(type(tensors))

<font size="4" color='yellow'>Reproducibility</font>

In [25]:
# It will give different result

tensor1 = torch.rand(2,2)
tensor2 = torch.rand(2,2)

print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

tensor([[0.5345, 0.7108],
        [0.8685, 0.7311]])
tensor([[0.2158, 0.7376],
        [0.8491, 0.1833]])
tensor([[False, False],
        [False, False]])


In [27]:
# It will give same result

torch.manual_seed(42)
tensor1 = torch.rand(2,2)

torch.manual_seed(42)
tensor2 = torch.rand(2,2)

print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[True, True],
        [True, True]])
